export * from './student.model';
export * from './student-evaluation.model';
export * from './installment.model';
export * from './attachment.model';
export * from './teacher.model';
export * from './requests/login.request';
export * from './generic-list.model';
export * from './generic-list-item.model';
export * from './class.model';
